export const GET_EXERCISES = "GET_EXERCISES";
export const GET_EXERCISES_ERROR = "GET_EXERCISES_ERROR";

export const CREATE_EXERCISE = "CREATE_EXERCISE";
export const CREATE_EXERCISE_ERROR = "CREATE_EXERCISE_ERROR";
